Repository graphite-project/graphite-web, pull requests merged in 2018-08, with the labels that each got.

#2331 Latest whitenoise is not supported by graphite
  requirements.txt
Labels: proposedfix

#2326 Fix get_real_metric_path for paths where an intermediate directory is a symlink
  webapp/graphite/finders/__init__.py
  webapp/tests/test_finders.py
Labels: proposedfix

#2322 convert prefetched values generator to reusable iterator
  webapp/graphite/render/datalib.py
Labels: proposedfix

#2339 add doc note about equal sign in rewrite rule's pattern
  docs/config-carbon.rst
Labels: documentation

#2314 Efficient reading
  webapp/graphite/local_settings.py.example
  webapp/graphite/readers/remote.py
  webapp/graphite/settings.py
Labels: enhancement

#2343 [1.1.x] skip ceres tests if not installed | Fix LDAP email address | Django 2 support | fix typo: matric -> metric in feeding-carbon.rst | Fixing typo in docs | improve performance of keepLastValue | expand k
  .travis.yml
  docs/config-webapp.rst
  docs/feeding-carbon.rst
  requirements.txt
  setup.py
  tox.ini
  webapp/graphite/account/ldapBackend.py
  webapp/graphite/account/views.py
  webapp/graphite/app_settings.py
  webapp/graphite/dashboard/views.py
  webapp/graphite/metrics/views.py
  webapp/graphite/render/functions.py
  webapp/graphite/render/hashing.py
  webapp/graphite/user_util.py
  webapp/tests/test_finders.py
  webapp/tests/test_functions.py
  webapp/tests/test_readers_ceres.py
Labels: backport

#2344 [1.1.x] Allow history tracking in composer | replace raise StopIteration with return pep-0479 | carbonlink: set the type of the recv buffer explicitly to bytes | clarify 'maxDataPoints' | Fail Hard p1 | Fail
  docs/render_api.rst
  webapp/content/js/composer.js
  webapp/graphite/carbonlink.py
  webapp/graphite/local_settings.py.example
  webapp/graphite/render/datalib.py
  webapp/graphite/render/hashing.py
  webapp/graphite/settings.py
  webapp/graphite/storage.py
  webapp/graphite/templates/composer.html
  webapp/tests/test_storage.py
Labels: backport
