Repository graphite-project/graphite-web, pull requests merged in 2018-12, with the labels that each got.

#2174 Add coverage for composer's send_email function
  webapp/tests/test_composer.py
Labels: enhancement, tests

#2375 Add a minValue option to nonNegativeDerivative and perSecond
  webapp/graphite/render/functions.py
  webapp/tests/test_functions.py
Labels: enhancement

#2398 [1.1.x] Do not use generator for jobs need to be run in pool | fix tests | remove unused import | move deserialize into remote finder | Multi-instance settings support | Fix default values in manage.py | Fix
  conf/graphite.wsgi.example
  docs/config-local-settings.rst
  docs/feeding-carbon.rst
  webapp/graphite/finders/remote.py
  webapp/graphite/readers/remote.py
  webapp/graphite/settings.py
  webapp/graphite/tags/localdatabase.py
  webapp/graphite/wsgi.py
  webapp/manage.py
  webapp/tests/test_finders_remote.py
  webapp/tests/test_readers_remote.py
Labels: backport

#2399 [1.1.x] Fix carbonlink queries for tagged series. | flake8 cleanup | With PR #2295 the top nav dashboard fails to render the default tree | Also have to override the input box value of '' with '*' because que
  .travis.yml
  docs/config-carbon.rst
  docs/render_api.rst
  setup.cfg
  webapp/content/js/dashboard.js
  webapp/graphite/finders/standard.py
  webapp/graphite/readers/rrd.py
  webapp/graphite/readers/utils.py
  webapp/graphite/render/datalib.py
  webapp/graphite/render/evaluator.py
  webapp/graphite/render/functions.py
  webapp/tests/test_composer.py
  webapp/tests/test_finders.py
  webapp/tests/test_functions.py
  webapp/tests/test_readers_util.py
Labels: backport

#2403 [1.1.x] Graphite release 1.1.5 | Changing release date
  docs/conf.py
  docs/releases.rst
  docs/releases/1_1_5.rst
Labels: backport
