Repository graphite-project/graphite-web, pull requests merged in 2018-09, with the labels that each got.

#2348 Release notes 1.1.4
  docs/releases.rst
  docs/releases/1_1_4.rst
Labels: documentation

#2349 [1.1.x] Release notes 1.1.4 | Grammar fixes
  docs/releases.rst
  docs/releases/1_1_4.rst
Labels: backport

#2317 html-encode text passed to Ext.Msg
  webapp/content/js/dashboard.js
Labels: enhancement
