Repository graphite-project/graphite-web, pull requests merged in 2019-10, with the labels that each got.

#2495 xFilesFactor is an optional parameter for removeEmptySeries
  webapp/graphite/render/functions.py
Labels: needs backport to 1.1.x

#2497 the callback parameter for groupByNode is optional
  webapp/graphite/render/functions.py
Labels: needs backport to 1.1.x

#2499 Removing function 'send_email'
  webapp/graphite/composer/urls.py
  webapp/graphite/composer/views.py
  webapp/graphite/settings.py
  webapp/tests/test_composer.py
Labels: needs backport to 0.9.x, needs backport to 1.0.x, needs backport to 1.1.x

#2502 Upgrading minimal Django version
  docs/requirements.txt
  tox.ini
Labels: needs backport to 1.1.x

#2503 [1.1.x] set package long description (#2407) | fix dashboard graph metric list icon paths with URL_PREFIX (#2424) | docs: for sql db migration to 1.1 recommend --fake-initial (#2425) | add tag formatting docs (#2426) | Update tags.rst (#242
  .travis.yml
  ISSUE_TEMPLATE.md
  MANIFEST.in
  docs/ceres.rst
  docs/client-apis.rst
  docs/config-database-setup.rst
  docs/config-local-settings.rst
  docs/install.rst
  docs/releases/1_1_1.rst
  docs/render_api.rst
  docs/requirements.txt
  docs/tags.rst
  docs/tools.rst
  requirements.txt
  setup.py
  tox.ini
  webapp/content/js/composer_widgets.js
  webapp/content/js/dashboard.js
  webapp/graphite/app_settings.py
  webapp/graphite/carbonlink.py
  webapp/graphite/composer/urls.py
  webapp/graphite/composer/views.py
  webapp/graphite/errors.py
  webapp/graphite/functions/params.py
  webapp/graphite/local_settings.py.example
  webapp/graphite/render/evaluator.py
  webapp/graphite/render/functions.py
  webapp/graphite/render/views.py
  webapp/graphite/settings.py
  webapp/graphite/tags/redis.py
  webapp/graphite/tags/utils.py
  webapp/graphite/templates/dashboard.html
  webapp/graphite/util.py
  webapp/tests/test_composer.py
  webapp/tests/test_functions.py
  webapp/tests/test_params.py
  webapp/tests/test_readers_remote.py
  webapp/tests/test_render.py
  webapp/tests/test_render_datalib.py
  webapp/tests/test_storage.py
  webapp/tests/test_tags.py
  webapp/tests/test_util.py
Labels: backport

#2505 [1.1.x] Prepare documentation for 1.1.6 release (#2504) | More changes (#2504) | Amended security issue description (#2504)
  docs/install.rst
  docs/releases.rst
  docs/releases/1_1_6.rst
Labels: backport
