Repository graphite-project/graphite-web, pull requests merged in 2020-02, with the labels that each got.

#2538 Parameter type int or inf
  webapp/graphite/functions/params.py
  webapp/graphite/render/functions.py
  webapp/tests/test_params.py
Labels: proposedfix

#2543 better error messages with type indications
  webapp/graphite/functions/params.py
  webapp/graphite/render/evaluator.py
Labels: needs backport to 1.1.x

#2542 fixes #2541
  webapp/graphite/functions/params.py
  webapp/graphite/render/functions.py
  webapp/tests/test_functions.py
Labels: needs backport to 1.1.x

#2549 Adding Hisser and Go-graphite buckytools in tools documentation
  docs/tools.rst
Labels: documentation

#2545 [1.1.x] Merge prefetched data. (#2507) | Fix AttributeError if parameter validation fails (#2510) | Taming lint (#2512) | relax enforcement of options sets in validation (#2513) | introduce paramtype for agg or series func (#2523) | add new
  .travis.yml
  docs/tags.rst
  docs/tools.rst
  requirements.txt
  setup.cfg
  setup.py
  tox.ini
  webapp/graphite/account/views.py
  webapp/graphite/browser/views.py
  webapp/graphite/composer/views.py
  webapp/graphite/dashboard/views.py
  webapp/graphite/events/models.py
  webapp/graphite/events/views.py
  webapp/graphite/functions/__init__.py
  webapp/graphite/functions/aggfuncs.py
  webapp/graphite/functions/params.py
  webapp/graphite/functions/safe.py
  webapp/graphite/render/datalib.py
  webapp/graphite/render/evaluator.py
  webapp/graphite/render/functions.py
  webapp/graphite/render/grammar.py
  webapp/graphite/tags/base.py
  webapp/graphite/tags/http.py
  webapp/graphite/tags/localdatabase.py
  webapp/graphite/tags/redis.py
  webapp/graphite/tags/utils.py
  webapp/graphite/templates/browserHeader.html
  webapp/graphite/templates/composer.html
  webapp/graphite/templates/dashboard.html
  webapp/graphite/templates/event.html
  webapp/graphite/templates/events.html
  webapp/graphite/util.py
  webapp/graphite/version/views.py
  webapp/tests/test_functions.py
  webapp/tests/test_params.py
  webapp/tests/test_render.py
  webapp/tests/test_tags.py
Labels: backport
